name: Pipeline CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Instalar dependencias
        run: |
          pip install flask
          
      - name: Test application import
        run: |
          python3 -m py_compile docker/app.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 # O la región que estés usando

      - name: Zip and Upload to S3
        run: |
          zip -r deploy.zip docker/
          aws s3 cp deploy.zip s3://bucket-proyecto-final-luis-588991582465/deploy.zip

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=i-0605c30715b4c7aa2" \
            --parameters 'commands=["aws s3 cp s3://bucket-proyecto-final-luis-588991582465/deploy.zip /home/ec2-user/","unzip -o /home/ec2-user/deploy.zip -d /home/ec2-user/","cd /home/ec2-user/docker && sudo docker-compose up -d --build"]'